<section class="mt-3 card card-body">
    <h1>Gerenciar Cursos</h1>

    <div class="mt-2">
        <a href="/cursos/novo" class="btn btn-outline-dark btn-sm">Novo Curso</a>

        <a href="/cursos/relatorio" class="btn btn-outline-dark btn-sm">Gerar PDF</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Categoria</th>
                <th>Carga Horaria</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
                    foreach ($cursos ?? [] as $curso) {
                        echo "
                            <tr>
                                <td>{$curso->id}</td>
                                <td>{$curso->nome}</td>
                                <td>{$curso->categoria}</td>
                                <td>{$curso->cargaHoraria}</td>
                                <td>
                                    <a href='/cursos/editar?id={$curso->id}' class='btn btn-outline-warning btn-sm'>Editar</a>
                                    <a href='/cursos/excluir?id={$curso->id}' class='btn btn-outline-danger btn-sm'>Excluir</a>
                                </td>
                            </tr>
                        ";
                    }
                // }
            ?>
        </tbody>
    </table>
</section>